### ISSUE TITLE
can't access some manifests under Safari

### ISSUE THREAD

**Issue by eroux** [ArchiveLabs/iiif.archivelab.org#53]
https://iiif.archivelab.org/iiif/rashodgson68/manifest.json in Safari 14 displays

![image_2020_12_11T17_06_47_934Z](https://user-images.githubusercontent.com/60868/101933480-8d09b680-3bdc-11eb-9105-398baf33355e.png)

Edit: it works in Chrome and Firefox

**Comment by garrettdashnelson** [comment]
Having this issue, too. (And hi, @eroux, from Slack!) It seems not to be exclusively a Safari issue, since cURL and Python Requests also show that the server response is malformed. 

Examples:

```zsh
~ % curl https://iiif.archivelab.org/iiif/rashodgson68$1/full/3500,/0/default.jpg
curl: (52) Empty reply from server
```

```python3
>>> import requests
>>> r = requests.get('https://iiif.archivelab.org/iiif/rashodgson68$1/full/3500,/0/default.jpg')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
````

**Comment by mprove** [comment]
My macOS Safari 11.1.2 cannot even open https://iiif.archivelab.org/ 
Same bug as shown in the screenshot above. Chrome and Firefox works fine.

**Comment by mekarpeles** [comment]
I think someone should buy `SiliconMind` a tea / beer because this suggestion of adding `ssl_session_cache shared:SSL:1m;` to  our `/etc/nginx/nginx.cong` seems to have done the trick:
https://stackoverflow.com/a/55067301

The original error is described here:
https://trac.nginx.org/nginx/ticket/235

@mprove + @eroux + @garrettdashnelson can you please check if the issue is now resolved?
I checked https://iiif.archivelab.org on a mac in safari and it seemed to server, not sure about the other pages.

@eroux if you're satisfied, I'll leave it to you to close the issue and or signal me to.

**Comment by edsu** [comment]
It works for me now...many, MANY thanks for this quick fix. It was directly effecting the Unlocking the Airwaves project at the University of Maryland: https://mith.umd.edu/airwaves/ If there is an email of thanks that can be written for the help you've provided and the service in general please let me know.

**Comment by mprove** [comment]
yeah! confirmed. The IIIF maps from internet archive now show up properly in all my browsers.
I have rectified 16 maps at the moment; here is a lovely one: 
https://mprove.de/chrono?q=51.17884,-1.82617&z=19.24&m=IAb28777542-16&r=-125&t=17&s=1&c=lia

**Comment by garrettdashnelson** [comment]
Yes, it works for me to. Thank you! This will finally unlock our ability to use BPL and LMEC collections that are hosted on IA in our various IIIF-powered interactive tools.

**Comment by eroux** [comment]
Great, works for our team too, thanks!
